name: format
# ワークフロー全体に適用する場合（推奨）
permissions:
  contents: read
on:
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Sync dependencies
        run: uv sync --dev

      - name: Run Black (check mode)
        run: uv run black --check .
